name: ffi_helper
description: Just some wrapper classes to make working with raw pointers and memory views a little simpler.
version: 1.4.1
homepage: https://gitlab.com/MagicGuitar/dart_ffi_helper

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  ffi: '>=1.0.0 <2.0.0'
  async: '>=2.4.0 <3.0.0'
  meta: '>=1.1.8 <2.0.0'

dev_dependencies:
  pedantic: '>=1.0.0 <2.0.0'
  
