name: ffi_helper
description: Some FFI helper classes
about: Provides some functionality to make working with the FFI a little easier
version: 1.0.0
homepage: https://gitlab.com/MagicGuitar/dart_ffi_helper
author: Marvin Hannott <marvinhannott@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
